package technology.positivehome.ihome.ai.controller;

import jakarta.validation.Valid;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import technology.positivehome.ihome.ai.orchestrator.ChatOrchestratorService;
import technology.positivehome.ihome.model.runtime.chat.ChatRequest;
import technology.positivehome.ihome.model.runtime.chat.ChatResponse;

/**
 * REST controller for the AI chat endpoint.
 * Accepts natural language messages from authenticated users and returns
 * responses generated by the DeepSeek LLM with home automation context.
 *
 * All endpoints require authentication via JWT.
 * <p>
 * The UI sends the full conversation history as a messages array.
 * The server prepends the system prompt and processes the conversation.
 */
@RestController
@RequestMapping("/api/v1/chat")
public class ChatController {

    private static final Logger log = LoggerFactory.getLogger(ChatController.class);

    private final ChatOrchestratorService orchestratorService;

    public ChatController(ChatOrchestratorService orchestratorService) {
        this.orchestratorService = orchestratorService;
    }

    /**
     * Processes a chat message from an authenticated user.
     * The user's JWT token determines which tools they can access:
     * - ADMIN users can both read status and control devices
     * - Non-admin users can only read status
     *
     * @param request        the chat request containing the conversation history
     * @param authentication the authenticated user (from JWT)
     * @return the LLM's response
     */
    @PreAuthorize("isAuthenticated()")
    @PostMapping
    public ResponseEntity<ChatResponse> chat(
            @Valid @RequestBody ChatRequest request,
            Authentication authentication) {

        ChatRequest.ChatMessage lastMessage = request.messages().get(request.messages().size() - 1);
        log.info("Chat request from user '{}': {}", authentication.getName(), lastMessage.text());

        String reply = orchestratorService.processMessage(request.messages(), authentication);

        return ResponseEntity.ok(ChatResponse.of(reply));
    }
}
