# HTTP Server
server:
  port: 8080 # HTTP (Tomcat) port

  logging:
    level:
      org:
        springframework:
          jdbc:
            core: OFF
          security: INFO

---
spring:
  thymeleaf:
    enabled: false
  profiles: default
  application:
    name: i-home
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    #    The following options we will receive from conf.yaml and corresponding command line options
    #    jdbc-url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    #    username: ${DB_USERNAME}
    #    password: ${DB_PASSWORD}
    hikari:
      #      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 30000
      maximum-pool-size: 10
      max-lifetime: 180000
      minimum-idle: 2

# Map the error path to error template (for Thymeleaf)
error:
  path=/error

### Configuring actuator endpoints (https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#production-ready-endpoint-custom-mapping)
management:
  endpoint:
    health:
      show-details: always

---

ihome:
  uri:
    proto: ${APP_PROTO}
    host: ${APP_HOST}
    port: ${APP_PORT}
  security.jwt:
    tokenExpirationTime: 15 # Number of minutes
    refreshTokenExpTime: 60 # Minutes
    tokenIssuer: https://positivehome.technology/
    tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus
