package technology.positivehome.ihome.domain.constant;

/**
 * Created by maxim on 6/27/19.
 **/
public enum ModuleProperty {
    UNDEFINED,
    LIGHT_TTL_IN_MINUTES,
    GARAGE_TEMPERATURE_SENSOR,
    OUTDOOR_TEMPERATURE_SENSOR,
    ALARM_SYSTEM_MODE_SENSOR,
    INDOOR_HUMIDITY_SENSOR,
    BATH_ROOM_HUMIDITY_SENSOR,
    CHECK_BATH_ROOM_HUMIDITY_INTERVAL,
    BATH_ROOM_MOTION_SENSOR,
    GARAGE_OUTDOOR_LUMINOSITY_SENSOR_ID,
    GARAGE_OUTDOOR_LUMINOSITY_MIN_VALUE,
    MAX_INDOOR_TEMPERATURE

}
