package technology.positivehome.ihome.server.processor;

/**
 * Created by maxim on 3/31/24.
 **/
public enum ChartType {
    INDOOR_TEMP,
    INDOOR_GF_TEMP,
    OUTDOOR_TEMP,
    GARAGE_TEMP,
    PRESSURE,
    BOILER_TEMP,
    LUMINOSITY,
    SYSTEM_LA,
    SYSTEM_HEAP_MAX,
    SYSTEM_HEAP_USAGE,
    EXT_POWER_VOLTAGE,
    EXT_POWER_CURRENT,
    EXT_POWER_FREQUENCY,
    EXT_POWER_CONSUMPTION,
    INT_POWER_VOLTAGE,
    INT_POWER_CURRENT,
    INT_POWER_FREQUENCY,
    INT_POWER_CONSUMPTION,
    INT_BCK_POWER_VOLTAGE,
    INT_BCK_POWER_CURRENT,
    INT_BCK_POWER_FREQUENCY,
    INT_BCK_POWER_CONSUMPTION

}
